config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  resources :users, only: %i[new create] 
  resources :boards, only: %i[index show new create edit destroy update] do
    resources :comments, only: %i[create edit destroy], shallow: true
    collection do
      get 'bookmarks'
    end
  end

  resources :bookmarks, only: %i[create destroy]
  get 'login', to: "user_sessions#new"
  post 'login', to: "user_sessions#create"
  delete 'logout', to: "user_sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
    validates :title, presence: true, length: { maximum: 255 }
    validates :body, presence: true, length: { maximum: 5000 }
    mount_uploader :board_image, BoardImageUploader
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :bookmarks, dependent: :destroy

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    belongs_to :user
    belongs_to :board
    
    validates :user_id, uniqueness: { scope: :board_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :body, presence: true, length: { maximum: 65_535 }
    belongs_to :user
    belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true

  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_boards, through: :bookmarks, source: :board

  def own?(object)
    id == object.user_id
  end

  def bookmark(board)
    bookmark_boards << board
  end

  def unbookmark(board)
    bookmark_boards.delete(board)
  end

  def bookmark?(board)
    bookmark_boards.include?(board)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :success, :danger
  
  private

  def not_authenticated
    redirect_to login_path, danger: t('defaults.flash_message.require_login')
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    def index
        @boards = Board.includes(:user).page(params[:page])
    end

    def show
        @board = Board.find(params[:id])
        @comment = Comment.new
        @comments = @board.comments.includes(:user).order(created_at: :desc)
    end

    def new
        @board = Board.new
    end

    def create
        @board = current_user.boards.build(board_params)
        if @board.save
            redirect_to boards_path, success: t('defaults.flash_message.created', item: Board.model_name.human)
        else
            flash.now[:danger] = t('defaults.flash_message.not_created', item: Board.model_name.human)
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @board = current_user.boards.find(params[:id])
    end

    def update
        @board = current_user.boards.find(params[:id])
      if @board.update(board_params)
        redirect_to board_path(@board), success: t('defaults.flash_message.updated', item: Board.model_name.human)
      else
        flash.now[:danger] = t('defaults.flash_message.not_updated', item: Board.model_name.human)
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
        board = current_user.boards.find(params[:id])
        board.destroy!
        redirect_to boards_path, success: t('defaults.flash_message.deleted', item: Board.model_name.human), status: :see_other
    end

    def bookmarks
        @bookmark_boards = current_user.bookmark_boards.includes(:user).order(created_at: :desc).page(params[:page])
        #bookmark_boardsはUserモデルから来ている。「ログインユーザーがブックマークした Board 一覧」という意味。
    end

private

    def board_params
        params.require(:board).permit(:title, :body, :board_image, :board_image_cache)
    end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

    def create
        @board = Board.find(params[:board_id])
        current_user.bookmark(@board)
    end

    def destroy
        @board = current_user.bookmarks.find(params[:id]).board
        current_user.unbookmark(@board)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    @comment.save
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(board_id: params[:board_id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    skip_before_action :require_login, only: %i[top]
    
    def top; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    skip_before_action :require_login, only: %i[new create]

    def new
        @user = User.new
    end

    def create
        @user = login(params[:email], params[:password])
        if @user
            redirect_to root_path, success: t('user_sessions.create.success')
        else
            @user ||= User.new
            flash.now[:danger] = t('user_sessions.create.failure')
            render :new, status: :unprocessable_entity
        end
    end
    def destroy
        logout
        redirect_to root_path, status: :see_other, success: t('user_sessions.destroy.success')
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: t('users.create.success')
    else
      flash.now[:danger] = t('users.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = '')
    base_title = 'RUNTEQ BOARD APP'
    title.present? ? "#{title} | #{base_title}" : base_title
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_board.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="board-id-<%= board.id %>">
    <div class="card">
      <%= image_tag board.board_image_url, class: "card-img-top", width: "300", height:"200" %>
      <div class="card-body">
        <div class="d-flex">
          <h4 class="card-title">
            <%= link_to board.title, board_path(board) %>
          </h4>
          <% if current_user.own?(board) %>
            <div class='ms-auto'>
              <%= link_to edit_board_path(board), id: "button-edit-#{board.id}" do %>
                <i class="bi bi-pencil-fill"></i>
              <% end %>
              <%= link_to board_path(board), id: "button-delete-#{board.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                <i class="bi bi-trash-fill"></i>
              <% end %>
            </div>
          <% else %>
            <%= render 'bookmark_buttons', { board: board } %>
          <% end %>
        </div>
        <ul class="list-inline">
          <li><i class="bi bi-person"></i><%= board.user.decorate.full_name %></li>
          <li><i class="bi bi-calendar"></i><%= l board.created_at, format: :short %></li>
        </ul>
        <p class="card-text">本文</p>
      </div>
    </div>
  </div>
</div>

app/views/boards/_bookmark.html.erb
<%= link_to bookmarks_path(board_id: board.id), id: "bookmark-button-for-board-#{board.id}", data: { turbo_method: :post } do %>
  <i class="bi bi-star"></i>
<% end %>

app/views/boards/_bookmark_buttons.html.erb
<div class='ms-auto'>
  <% if current_user.bookmark?(board) %>
    <%= render 'unbookmark', { board: board } %>
  <% else %>
    <%= render 'bookmark', { board: board } %>
  <% end %>
</div>

app/views/boards/_form.html.erb
<%= form_with model: board do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="mb-3">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control", rows: "10" %>
  </div>
  <div class="mb-3">
    <%= f.label :board_image %>
    <%= f.file_field :board_image, class: "form-control", accept: 'image/*' %>
    <%= f.hidden_field :board_image_cache %>
  </div>
  <%= f.submit nil, class: "btn btn-primary" %>
<% end %>

app/views/boards/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(board_id: board.id)), id: "unbookmark-button-for-board-#{board.id}", data: { turbo_method: :delete } do %>
  <i class="bi bi-star-fill"></i>
<% end %>

app/views/boards/bookmarks.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <form>
        <div class="input-group mb-3"><input class="form-control" placeholder="検索ワード" type="search"/>
          <div class="input-group-append"><input type="submit" value="検索" class="btn btn-primary"/></div>
        </div>
      </form>
    </div>
  </div>
  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @bookmark_boards.present? %>
          <%= render @bookmark_boards %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <%= paginate @bookmark_boards, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/boards/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', board: @board %>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <form>
        <div class="input-group mb-3"><input class="form-control" placeholder="検索ワード" type="search"/>
          <div class="input-group-append"><input type="submit" value="検索" class="btn btn-primary"/></div>
        </div>
      </form>
    </div>
  </div>
  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @boards.present? %>
          <%= render @boards %>
        <% else %>
          <div class="mb-3">掲示板がありません</div>
        <% end %>
      </div>
      <%= paginate @boards, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<% content_for(:title, t('.title')) %>
<!-- エラーメッセージの表示 -->
<%= render "shared/error_messages", object: @board %>

<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= form_with model: @board, class: "new_board" do |f| %>
        <div class="mb-3">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :body %>
          <%= f.text_area :body, class: "form-control", rows: "10" %>
        </div>
        <div class="mb-3">
          <%= f.label :board_image %>
          <%= f.file_field :board_image, class: "form-control", accept: 'image/*' %>
          <%= f.hidden_field :board_image_cache %>
        </div>
        <%= f.submit nil, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<% content_for(:title, @board.title) %>
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <article class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-3">
              <%= image_tag @board.board_image_url, width: "300", height: "200", class: "card-img-top img-fluid" %>
            </div>
            <div class="col-md-9">
              <h3 style="display: inline;"><%= @board.title %></h3>
              <ul class="list-inline">
                <li class="list-inline-item"><%= "by #{@board.user.decorate.full_name}" %></li>
                <li class="list-inline-item"><%= l @board.created_at, format: :long %></li>
              </ul>
              <% if current_user.own?(@board) %>
              <div class='d-flex justify-content-end'>
                <%= link_to edit_board_path(@board), id: "button-edit-#{@board.id}" do %>
                  <i class='bi bi-pencil-fill'></i>
                <% end %>
                <%= link_to board_path(@board), id: "button-delete-#{@board.id}", class: "ms-2", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                  <i class="bi bi-trash-fill"></i>
                <% end %>
              </div>
              <% end %>
            </div>
          </div>
          <p><%= simple_format(@board.body) %></p>
        </div>
      </article>
    </div>
  </div>
  <%= render 'comments/form', comment: @comment, board: @board %>
  <!-- コメント一覧の表示も追加することをお勧めします -->
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <table class="table">
        <tbody id="table-comment">
          <%= render @comments %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/bookmarks/create.turbo_stream.erb
<%= turbo_stream.replace "bookmark-button-for-board-#{@board.id}" do %>
  <%= render 'boards/unbookmark', board: @board %>
<% end %>

app/views/bookmarks/destroy.turbo_stream.erb
<%= turbo_stream.replace "unbookmark-button-for-board-#{@board.id}" do %>
  <%= render 'boards/bookmark', board: @board %>
<% end %>

app/views/comments/_comment.html.erb
<tr id="comment-<%= comment.id %>">
  <td style="width: 60px">
    <%= image_tag "sample", width: "50", height: "50", class: "rounded-circle" %>
  </td>
  <td>
    <h3 class="small"><%= comment.user.decorate.full_name %></h3>
    <p><%= simple_format(comment.body) %></p>
  </td>
  <% if current_user.own?(comment) %>
    <td class="action">
      <ul class="list-inline justify-content-center" style="float: right;">
        <li class="list-inline-item">
          <%= link_to "#", class: "edit-comment-link" do %>
            <i class="bi bi-pencil-fill"></i>
          <% end %>
        </li>
        <li class="list-inline-item">
          <%= link_to comment_path(comment), class: "delete-comment-link", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
            <i class="bi bi-trash-fill"></i>
          <% end %>
        </li>
      </ul>
    </td>
  <% end %>
</tr>

app/views/comments/_form.html.erb
<div class="row mb-3" id="comment-form">
  <div class="col-lg-8 offset-lg-2">
    <%= form_with model: comment, url: board_comments_path(board) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control mb-3", row: "4", placeholder: Comment.human_attribute_name(:body) %>
      <%= f.submit t('defaults.post'), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/comments/create.turbo_stream.erb
<% if @comment.errors.present? %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: @comment, board: @comment.board %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "table-comment" do %>
    <%= render 'comments/comment', comment: @comment %>
  <% end %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: Comment.new, board: @comment.board %>
  <% end %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment-#{@comment.id}" do %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render "shared/header" %>
    <% else %>
      <%= render "shared/before_login_header" %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to t('header.login'), login_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12'>
        <div class='copyright'>
          <p>Copyright © 2019. RUNTEQ</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to '/', class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class='nav-item dropdown dropdown-slide'>
          <%= link_to t('header.board'), '#', class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-board-menu' %>
          <div class='dropdown-menu dropdown-menu-end'>
            <%= link_to t('header.board_index'), boards_path, class: 'dropdown-item' %>
            <%= link_to t('header.create_board'), new_board_path, class: 'dropdown-item' %>
          </div>
        </li>

        <li class='nav-item'>
          <%= link_to t('header.bookmark_index'), bookmarks_boards_path, class: 'nav-link' %>
        </li>

        <li class='nav-item dropdown dropdown-slide'>
          <%= link_to '#', class: 'nav-link', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-profile' do %>
            <%= image_tag 'sample.jpg', class: 'rounded-circle mr15', width: '40', height: '40' %>
          <% end %>
          <div class='dropdown-menu dropdown-menu-end'>
            <div class='dropdown-item'>current_user.decorate.full_name</div>
            <div class='dropdown-divider'></div>
            <%= link_to t('header.profile'), '#', class: 'dropdown-item' %>
            <%= link_to t('header.logout'), logout_path, class: 'dropdown-item', data: { turbo_method: :delete } %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/static_pages/top.html.erb
<div class="top-wrapper">
  <div class="top-inner-text">
    <h1>RUNTEQ BOARD APP</h1>
  </div>
</div>

app/views/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>
<!-- エラーメッセージの表示 -->
<%= render "shared/error_messages", object: @user %>

<div class="container">
  <div class="row">
    <div class=" col-md-10 col-lg-8 mx-auto">
      <h1><%= t('.title') %></h1>
      <%= form_with url: login_path do |f| %>
        <div class="mb-3">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <%= f.submit t('.login'), class: "btn btn-primary" %>
      <% end %>
      <div class='text-center'>
        <%= link_to t('.to_register_page'), new_user_path %>
        <%= link_to t('.password_forget'), '#' %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% content_for(:title, t('.title')) %>
<!-- エラーメッセージの表示 -->
<%= render "shared/error_messages", object: @user %>

<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1>新規登録</h1>
      <%= form_with model: @user do |f| %>
        <div class="mb-3">
          <%= f.label :last_name, class: "form-label" %>
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :first_name, class: "form-label" %>
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :email, class: "form-label" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: "form-label" %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, class: "form-label" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
          <%= f.submit class: "btn btn-primary" %>
      <% end %>
      <div class='text-center'>
        <%= link_to t('.to_login_page'), login_path %>
      </div>
    </div>
  </div>
</div>